[package]
name = "rs-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
#syscalls = { version = "0.6.18", default-features = false, features = ["riscv32"] }

[profile.release]
opt-level = 3
panic = "abort"
lto = "fat"
overflow-checks = false
